name: Dev
on:
  push:
    branches-ignore:
      - master
jobs:
  handle-skip-ci:
    name: Test Build
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - run: echo "Skipping CI because of this commit message = ${{ github.event.head_commit.message }}"
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run lint
      run: npm run lint
    - name: Run test
      run:  npm run test -- --coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
    - name: Test build release
      run: npm run build

